name: DevOps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:


jobs: 
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Prueba, CI

      - name: Run a multi-line script
        run:
          echo add other actions to build,
          echo test, and deploy your proyect.

